
version: 2

models:
  - name: my_1st_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_2nd_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  
  - name: my_3rd_dbt_model
    description: "Third model"
    columns:
      - name: id
        description: "The pk"
  
  - name: the_4th_model
    columns:
      - name: id
        description: "This ones pk"
        