
version: 2

models:
  - name: my_1st_dbt_model
    description: "Should not be here...."
    columns:
      - name: id
        description: "The primary key for this table X"
        tests:
          - unique
          - not_null
  
  - name: my_4th_dbt_model
    columns:
      - name: id
        description: "This ones pk"
      - name: name
        description: "a random const"

  # missmatch name
  - name: the_5th_model
    columns:
      - name: model1_id
        description: "pk of 1st model"
      - name: model4_id
        description: "pk of 4th model"
        